version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: mal
    depends_on:
      - db
      - db2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JACKSON_DATE-FORMAT=yyyy-MM-dd HH:mm:ss
      - SPRING_DATA_MONGODB_URI=mongodb://db2:27017/test

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  db2:
    image: 'mongo:3.2.4'
    container_name: db2
    ports:
      - 27017:27017
